version: "3"

services:
  host:
    container_name: host-app
    build:
      context: .
      dockerfile: ./apps/host-app/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  remote:
    container_name: remote-app
    build:
      context: .
      dockerfile: ./apps/remote-app/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    ports:
      - 3002:3002
    networks:
      - app_network
  mongo:
    container_name: db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

volumes:
  mongo-data:

networks:
  app_network:
    driver: bridge 
