version: "3"

services:
  host:
    container_name: host-app
    build:
      context: .
      dockerfile: ./apps/host-app/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  remote:
    container_name: remote-app
    build:
      context: .
      dockerfile: ./apps/remote-app/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
